# Generated by Django 5.1.7 on 2025-03-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('job_offer_link', models.URLField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mission', models.CharField(choices=[('standard', 'Standard'), ('ed-tech', 'Ed-Tech'), ('ecology', 'Ecology'), ('energy', 'Energy'), ('enabling_connections', 'Connexion'), ('géographies', 'Géographies'), ('aménagement_du_territoire', 'Aménagement du territoire'), ('histoire', 'Histoire'), ('politique', 'Politique'), ('education', 'Education'), ('sécurité', 'Sécurité'), ('fonction_publique', 'Fonction publique'), ('animaux', 'Animaux'), ('féminisme', 'Féminisme'), ('sexualité', 'Sexualité'), ('social_justice', 'Social-justice'), ('arts', 'Arts'), ('sport', 'Sport'), ('esn', 'ESN'), ('justice', 'Justice'), ('immobilier', 'Immobilier'), ('cybersecurite', 'Cybersecurité')], max_length=50)),
                ('python', models.BooleanField(default=False)),
                ('django', models.BooleanField(default=False)),
                ('html_css', models.BooleanField(default=False)),
                ('javascript', models.BooleanField(default=False)),
                ('typescript', models.BooleanField(default=False)),
                ('react', models.BooleanField(default=False)),
                ('next', models.BooleanField(default=False)),
                ('tailwind', models.BooleanField(default=False)),
                ('node', models.BooleanField(default=False)),
                ('vuejs', models.BooleanField(default=False)),
                ('devops', models.BooleanField(default=False)),
                ('java', models.BooleanField(default=False)),
                ('angular', models.BooleanField(default=False)),
                ('php', models.BooleanField(default=False)),
                ('ruby', models.BooleanField(default=False)),
                ('go', models.BooleanField(default=False)),
            ],
        ),
    ]
