# Generated by Django 5.1.7 on 2025-03-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covergenerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rh_interview', 'RH interview'), ('tech_iterview', 'Tech interview'), ('final_interview', 'Final interview'), ('declined', 'Declined'), ('hired', 'Hired')], default='pending', max_length=50),
        ),
    ]
