# Generated by Django 5.1.7 on 2025-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covergenerator', '0002_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='bdd',
            field=models.BooleanField(default=False),
        ),
    ]
